---
title: 'R Practice: Spatial Data and Making Maps'
author: "Michelle Mohr"
date: "2023-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r load libraries}
library(readr)
library(dplyr)
library(sf)
library(ggplot2)
library(scales)
library(leaflet)
library(ggmap)

```

## Download Data

## Read Data

```{r read data}
pika <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-nwt.268.1&entityid=43270add3532c7f3716404576cfb3f2c")
elevation <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-nwt.268.1&entityid=6a10b35988119d0462837f9bfa31dd2f")
```

## View Data

```{r view data options}
# view data in a spreadsheet-style viewer
View(pika)

# returns dimensions of the dataframe by number of rows and number of cols
dim(pika)

# returns the top six rows of the dataframe
head(pika)

# returns all the columns and some info about the cols
glimpse(pika)

# similar to glimpse but returns some summary statistics about the cols
summary(pika)

# returns column names 
names(pika)

# returns unique values in a column. In this case we can see all the different bird species IDs
unique(pika$Site)
```

## Clean and Wrangle Data

### Clean and Wrangle Pika Data

```{r remove columns}
pika_clean <- pika %>% 
  select(-Notes,
         -Vial,
         -Plate,
         -Biweek)
#### by using - we remove those columns 
```

```{r convert data types}
pika_clean <- pika_clean %>% 
  mutate(Station = as.factor(Station),
         Site = as.factor(Site),
         Sex = as.factor(Sex)
         )
### by using as.factor we change the class from character to a factor
```

```{r spell out the abbreviations in Site}
pika_clean <- pika_clean %>% 
  mutate(Site = recode(
    Site,
    "CG" = "Cable Gate",
    "WK" = "West Knoll",
    "LL" = "Long Lake"
  ))
## by using mutate, we can change the names within the character
```

```{r reorganizing columns to be next to eachother}
pika_clean <- pika_clean %>%  
  relocate(Site, .before = Station) %>% 
  relocate(Sex, .after = UTM_Northing)
## by using relocate, we can move columns around in our data table 
```

### Clean and Wrangle Elevation Data

```{r show only specific columns}
elevation_clean <- elevation %>% 
  select(Station, Elev_M) %>% 
 # by using mutate, we can change the Station class of character to factor 
## you can check that the conversation worked using class(elevation_clean$Station)
  mutate(Station = as.factor(Station))
# by selecting (Station, Elev_M) we only observe those two columns
## can view the clean data using View(elevation_clean) in the Console Window

```

```{r Join data}
# two ways to join data

## using the pipe
pikas <- pika_clean %>% 
  full_join(y = elevation_clean,
            by = 'Station')

```

## Spatial Exploration and Making Maps

```{r converting to simple features}
pikas_sf <- st_as_sf(x = pikas,
                     coords = c("UTM_Easting", "UTM_Northing"))

```

## Setting a Coordinate Reference System (CRS)

```{r setting the CRS geometry column}
pikas_sf <- st_set_crs(pikas_sf, 26913)
# this EPSG code is for North America, but knowing that the Niwot Ridge Research Station is located in north-central Colorado, you could search for this region on epsg.io and use a more local EPSG code. However, if you want to change the CRS after setting it here, you will need to use st_transform() because replacing the EPSG code in st_set_crs() will not reproject the data.
```

## Plotting Points

```{r plotting points using ggplot and geom_sf()}
ggplot(data = pikas_sf) +
    geom_sf()
## basic maps
```

```{r make it pretty}
ggplot(data = pikas_sf) +
    geom_sf(aes(color = Site, shape = Site), alpha = 0.6) +
    theme_minimal() +
    labs(
        title = "Location of Pika Sampling Stations",
        subtitle = "Niwot Ridge LTER",
        x = "Latitude (Degrees)",
        y = "Longitude (Degrees)"
    ) +
    theme(axis.text.x = element_text(angle = 30)) # tilt x-axis text so that the labels don't overlap
```

## Adding a basemap

```{r base map}
pikas_sf_4326 <- st_transform(pikas_sf, 4326)
```

```{r boundary box}
nwt_bbox <- c(left = -105.65, bottom = 40.04, right = -105.55, top = 40.1)
```

```{r mapping basemap}
nwt_basemap <- ggmap::get_stamenmap(nwt_bbox, zoom = 13, 
                                    maptype = "terrain")

ggmap(nwt_basemap)
```

```{r base map with points}
ggmap(nwt_basemap) +
    geom_sf(pikas_sf_4326, 
            mapping = aes(color = Site, shape = Site), 
            inherit.aes = FALSE)
```

```{r make it pretty, again}
ggmap(nwt_basemap) +
    geom_sf(pikas_sf_4326,
            mapping = aes(color = Site, shape = Site),
            inherit.aes = FALSE) +
    theme_minimal() +
    labs(
        title = "Location of Pika Sampling Stations",
        subtitle = "Niwot Ridge LTER", 
        x = "Longitude (Degrees)",
        y = "Latitude (Degrees)"
    ) +
  theme(
    plot.title = element_text(hjust = 0.5))
    # choosing colors to make sure points are visible
    scale_color_manual(values = c("black", "red", "purple")) 
```

## Make and interactive map using leaflet
```{r make and interactive map }
leaflet() %>% 
  addTiles() %>% 
  addCircles(data = pikas_sf_4326, label = ~Station)
#### If you want to add more styling to your interactive map, review the leaflet sections in Intro to Data Viz, Using sf for Spatial Data & Intro to Map Making, or check out the leaflet cheatsheet. 
###### https://github.com/rstudio/cheatsheets/blob/main/leaflet.pdf
```

